### ISSUE TITLE
Merge in the main repository?

### ISSUE THREAD

**Issue by Neustradamus** [ForNeVeR/kaiwa#238]
@ForNeVeR: Are you ready to merge all your changes in the main repository?

**Comment by ForNeVeR** [comment]
I think I already had this discussion with someone over the years, but I'm glad to present my arguments.

There's a couple of points on the proposed "upstream merge":
1. First, our Kaiwa fork has been started by agressively _removing_ the upstream features that were creating maintenance/build problems (e.g. something LDAP-related).
2. We proceeded with agressively refactoring the existing code and rewriting it into other language (TypeScript) not every upstream author (I suppose) would approve.
3. And, finally, we have started a big React rewrite adventure (I'm not sure how it ended up; probably not very well).

Current code base in the dev branch is broken, so we shouldn't merge to anywhere (if you need any particular reason), but even at stage 1 I'd say that we shouldn't even try merging back, since the changes were _agressive removal_ of unnecessary (for the purpose of the fork) features.

I don't think we should merge.
